### ISSUE TITLE
FAIR checklist - Project documentation

### ISSUE THREAD

**Issue by edvinskis** [hiddeoff/crisprzip#1]
_Essential_  
- [x] [README](https://www.makeareadme.com)
- [x] Apply a TU Delft pre-approved [LICENSE](https://zenodo.org/records/4629635)
- [x] [CITATION](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)
