### ISSUE TITLE
FAIR checklist - Software documentation

### ISSUE THREAD

**Issue by edvinskis** [hiddeoff/crisprzip#2]
_Essential_  
- [x] Source code documentation ([docstrings](https://numpydoc.readthedocs.io/en/latest/format.html))
- [x] Document your project dependencies
- [x] Installation instructions
- [x] User documentation

_Recommended_  
- [x] Developer documentation and setup
- [x] Examples and tutorials (e.g. Jupyter Notebooks)

_Optional_
- [x] Documentation tools ([Sphinx](https://coderefinery.github.io/documentation/sphinx/), [JupyterBook](https://jupyterbook.org/intro.html), [Quarto](https://quarto.org/docs/guide/))
- [x] Build an [API reference](https://developer.lsst.io/python/numpydoc.html) from docstrings
- [x] Hosting ([GitHub Pages](https://pages.github.com/), [Readthedocs](https://readthedocs.org/))
