### ISSUE TITLE
FAIR checklist - Version control

### ISSUE THREAD

**Issue by edvinskis** [hiddeoff/crisprzip#4]
_Essential_
- [x] Use [git](https://www.atlassian.com/git) as a version control system 
- [x] Upload your project on [GitHub](https://github.com/) or [TU Delft GitLab](https://gitlab.tudelft.nl/)

_Recommended_  
- [x] Make your repository [public](https://coderefinery.github.io/social-coding/)
- [x] Consider your [branch hygiene](https://coderefinery.github.io/git-branch-design/)
- [x] Use a branching model (e.g. [GitFlow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow))
- [x] Use [meaningful commit messages](https://www.git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines)
