### ISSUE TITLE
FAIR checklist - Software quality

### ISSUE THREAD

**Issue by edvinskis** [hiddeoff/crisprzip#5]
_Essential_
- [x] [Organize](https://coderefinery.github.io/reproducible-research/organizing-projects/) your project for reproducibility
- [x] [Record and manage](https://coderefinery.github.io/reproducible-research/dependencies/) your software dependencies 

_Recommended_
- [x] Make [refactoring](https://refactoring.guru/refactoring) part of your workflow
- [x] Follow [best coding practices](https://alan-turing-institute.github.io/rse-course/html/module07_construction_and_design/index.html)

_Recommended for Python_
- [x] Follow [PEP8 guidelines](https://realpython.com/python-pep8/)
- [x] Use a tool for dependency management (e.g. [poetry](https://the-turing-way.netlify.app/reproducible-research/renv/renv-package.html))
- [x] Use linter (e.g. [pylint](https://pypi.org/project/pylint/), [flake8](https://pypi.org/project/flake8/))
- [x] Use a formatter (e.g. [black](https://github.com/psf/black))
